### ISSUE TITLE
There is a problem with prefixes in the database.

### ISSUE THREAD

**Issue by artur002** [toteph42/ident_switch#5]
If you prefix the database in the Roundcube configuration, an error pops up during installation when creating the database. Actually, the whole point is that the SQL query itself does not take this parameter into account. If you edit it with your own hands, then everything is fine.

**Comment by toteph42** [comment]
Are you using MySQL, SQLite or PostGres? Please Post Version (Roundcube, plugin) and `erros.log`.

**Comment by artur002** [comment]
The error is that the sql query (in the file) does not take into account
the database prefix. If you look at the Mysql query file, the default table
name data is written there. It is enough to generate table names taking
into account the prefix. So that the key binding does not occur with
"name_table", but with "prefixDB_in_rcube_config" + "name_table". The logs
were not saved, I fixed it myself. But I decided to share it here. You can
check for yourself by specifying the db prefix in the rcube settings.
чт, 22 февр. 2024 г., 15:02 toteph42 ***@***.***>:

**Comment by toteph42** [comment]
Hi,
I check it out. The problem is located inside Roundcube installation (especially in `rcube_db.php.` There is the prefix add to some statements. Unfortunately not for the `CONSTRAINT` statement I use. I can't fix that. You should share it at Roundcube core, because I found a lot of other plugins having the same problem.
